baseURL = 'https://sebastianemery.com/'
languageCode = 'en-us'
title = 'Andrew Meyer'
theme = 'ananke'
SectionPagesMenu = "main"
enableRobotsTXT = true
[services]
[services.disqus]
shortname = 'andrew-meyer-com'
[sitemap]
 chagefreq = "weekly"
 filename = "sitemap.xml"
 priority = 0.5

[[params.ananke_socials]]
name = "YouTube"
url = "https://www.youtube.com/@andrew-meyer-author"
[[params.ananke_socials]]
name = "Twitter"
url = "https://bsky.app/profile/andrew-meyer.bsky.social"
[[params.ananke_socials]]
name = "patreon"
url = "https://patreon.com/andrewmeyer"
[markup.goldmark.renderer]
unsafe = true