baseURL = 'https://andrew-meyer.com/'
languageCode = 'en-us'
title = 'Andrew Meyer'
theme = 'ananke'
SectionPagesMenu = "main"
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/andrewmeyer"
[[params.ananke_socials]]
name = "patreon"
url = "https://patreon.com/andrewmeyer"
